"""add_subcategory_columns

Revision ID: 1403072337ae
Revises: c944b7a26a25
Create Date: 2026-02-16 13:08:42.709388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1403072337ae'
down_revision: Union[str, Sequence[str], None] = 'c944b7a26a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('subcategory_secondary', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'subcategory_secondary')
    op.drop_column('questions', 'subcategory')
    # ### end Alembic commands ###
