"""add_is_ai_generated_to_questions

Revision ID: c944b7a26a25
Revises: c3237767ce71
Create Date: 2026-02-15 19:26:17.283889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c944b7a26a25'
down_revision: Union[str, Sequence[str], None] = 'c3237767ce71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_ai_generated', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_ai_generated')
    # ### end Alembic commands ###
